In [ ]:
import torch
import pandas as pd
import os
from PIL import Image
from transformers import LlavaProcessor, LlavaForConditionalGeneration
from tqdm import tqdm

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
!unzip "/content/drive/MyDrive/place-pulse-2.0 (2).zip" -d /content/

Streaming output truncated to the last 5000 lines.
  inflating: /content/__MACOSX/images/._35.749498_139.709852_513e6c3efdc9f0358700c139_Tokyo.JPG
  inflating: /content/images/44.423834_26.025045_5140ceb7fdc9f0492600308a_Bucharest.JPG
  inflating: /content/__MACOSX/images/._44.423834_26.025045_5140ceb7fdc9f0492600308a_Bucharest.JPG
  inflating: /content/images/52.218359_20.909351_50f42b52fdc9f065f0001369_Warsaw.JPG
  inflating: /content/__MACOSX/images/._52.218359_20.909351_50f42b52fdc9f065f0001369_Warsaw.JPG
  inflating: /content/images/55.799112_37.779071_513e1dc9fdc9f03587009aba_Moscow.JPG
  inflating: /content/__MACOSX/images/._55.799112_37.779071_513e1dc9fdc9f03587009aba_Moscow.JPG
  inflating: /content/images/41.955114_-87.758089_513cb5dbfdc9f035870009a6_Chicago.JPG
  inflating: /content/__MACOSX/images/._41.955114_-87.758089_513cb5dbfdc9f035870009a6_Chicago.JPG
  inflating: /content/images/39.757205_-105.109594_513d6b71fdc9f03587004d07_Denver.JPG
  inflating: /content/__MACOSX/images/._39.757205_-105.109594_513d6b71fdc9f03587004d07_Denver.JPG
  inflating: /content/images/40.002461_-75.197911_514228edfdc9f049260087e6_Philadelphia.JPG
  inflating: /content/__MACOSX/images/._40.002461_-75.197911_514228edfdc9f049260087e6_Philadelphia.JPG
  inflating: /content/images/53.374703_-6.099119_5140d8cafdc9f04926003aae_Dublin.JPG
  inflating: /content/__MACOSX/images/._53.374703_-6.099119_5140d8cafdc9f04926003aae_Dublin.JPG
  inflating: /content/images/33.734605_-84.243909_513d9d68fdc9f0358700806b_Atlanta.JPG
  inflating: /content/__MACOSX/images/._33.734605_-84.243909_513d9d68fdc9f0358700806b_Atlanta.JPG
  inflating: /content/images/-33.487220_-70.674570_513d803bfdc9f035870076b5_Santiago.JPG
  inflating: /content/__MACOSX/images/._-33.487220_-70.674570_513d803bfdc9f035870076b5_Santiago.JPG
  inflating: /content/images/40.016617_-75.057056_51422aeefdc9f049260089be_Philadelphia.JPG
  inflating: /content/__MACOSX/images/._40.016617_-75.057056_51422aeefdc9f049260089be_Philadelphia.JPG
  inflating: /content/images/-33.891762_18.644694_513cde28fdc9f035870020de_CapeTown.JPG
  inflating: /content/__MACOSX/images/._-33.891762_18.644694_513cde28fdc9f035870020de_CapeTown.JPG
  inflating: /content/images/33.714321_-84.483689_513d7cb8fdc9f03587006fae_Atlanta.JPG
  inflating: /content/__MACOSX/images/._33.714321_-84.483689_513d7cb8fdc9f03587006fae_Atlanta.JPG
  inflating: /content/images/40.475950_-3.744389_514091b5fdc9f04926000577_Madrid.JPG
  inflating: /content/__MACOSX/images/._40.475950_-3.744389_514091b5fdc9f04926000577_Madrid.JPG
  inflating: /content/images/19.481818_-99.082415_51414fd1fdc9f04926007bb5_MexicoCity.JPG
  inflating: /content/__MACOSX/images/._19.481818_-99.082415_51414fd1fdc9f04926007bb5_MexicoCity.JPG
  inflating: /content/images/35.622521_139.757157_513e6b27fdc9f0358700bfc0_Tokyo.JPG
  inflating: /content/__MACOSX/images/._35.622521_139.757157_513e6b27fdc9f0358700bfc0_Tokyo.JPG
  inflating: /content/images/39.985863_-75.199298_50f61672beb2fed910000870_Philadelphia.JPG
  inflating: /content/__MACOSX/images/._39.985863_-75.199298_50f61672beb2fed910000870_Philadelphia.JPG
  inflating: /content/images/40.425841_-3.545976_51408adafdc9f0358700e7ef_Madrid.JPG
  inflating: /content/__MACOSX/images/._40.425841_-3.545976_51408adafdc9f0358700e7ef_Madrid.JPG
  inflating: /content/images/53.322282_-6.254344_5140d72afdc9f0492600376f_Dublin.JPG
  inflating: /content/__MACOSX/images/._53.322282_-6.254344_5140d72afdc9f0492600376f_Dublin.JPG
  inflating: /content/images/41.860881_12.403405_51409c55fdc9f049260011a3_Rome.JPG
  inflating: /content/__MACOSX/images/._41.860881_12.403405_51409c55fdc9f049260011a3_Rome.JPG
  inflating: /content/images/59.282571_18.074964_50f55e0cfdc9f065f0004a49_Stockholm.JPG
  inflating: /content/__MACOSX/images/._59.282571_18.074964_50f55e0cfdc9f065f0004a49_Stockholm.JPG
  inflating: /content/images/-33.903958_18.619009_513cc194fdc9f035870014b3_CapeTown.JPG
  inflating: /content/__MACOSX/images/._-33.903958_18.619009_513cc194fdc9f035870014b3_CapeTown.JPG
  inflating: /content/images/29.745146_-95.456796_513cbf04fdc9f03587001227_Houston.JPG
  inflating: /content/__MACOSX/images/._29.745146_-95.456796_513cbf04fdc9f03587001227_Houston.JPG
  inflating: /content/images/39.746908_-104.867009_513d6bebfdc9f03587004e36_Denver.JPG
  inflating: /content/__MACOSX/images/._39.746908_-104.867009_513d6bebfdc9f03587004e36_Denver.JPG
  inflating: /content/images/-33.917682_151.147933_50f44852fdc9f065f0003e2f_Sydney.JPG
  inflating: /content/__MACOSX/images/._-33.917682_151.147933_50f44852fdc9f065f0003e2f_Sydney.JPG
  inflating: /content/images/-33.850320_18.679032_513ced3dfdc9f035870023c9_CapeTown.JPG
  inflating: /content/__MACOSX/images/._-33.850320_18.679032_513ced3dfdc9f035870023c9_CapeTown.JPG
  inflating: /content/images/35.767372_139.747803_513f136bfdc9f0358700cae2_Tokyo.JPG
  inflating: /content/__MACOSX/images/._35.767372_139.747803_513f136bfdc9f0358700cae2_Tokyo.JPG
  inflating: /content/images/-37.942226_145.016095_514141f6fdc9f04926006244_Melbourne.JPG
  inflating: /content/__MACOSX/images/._-37.942226_145.016095_514141f6fdc9f04926006244_Melbourne.JPG
  inflating: /content/images/-33.855750_151.042366_50f447dafdc9f065f0003b62_Sydney.JPG
  inflating: /content/__MACOSX/images/._-33.855750_151.042366_50f447dafdc9f065f0003b62_Sydney.JPG
  inflating: /content/images/33.829763_-84.256924_513d78cafdc9f035870062ac_Atlanta.JPG
  inflating: /content/__MACOSX/images/._33.829763_-84.256924_513d78cafdc9f035870062ac_Atlanta.JPG
  inflating: /content/images/44.513377_25.976987_5140caeefdc9f049260029c3_Bucharest.JPG
  inflating: /content/__MACOSX/images/._44.513377_25.976987_5140caeefdc9f049260029c3_Bucharest.JPG
  inflating: /content/images/41.745377_-87.646310_513cc95cfdc9f03587001c15_Chicago.JPG
  inflating: /content/__MACOSX/images/._41.745377_-87.646310_513cc95cfdc9f03587001c15_Chicago.JPG
  inflating: /content/images/-33.951759_18.655984_513cea53fdc9f03587002339_CapeTown.JPG
  inflating: /content/__MACOSX/images/._-33.951759_18.655984_513cea53fdc9f03587002339_CapeTown.JPG
  inflating: /content/images/52.538137_13.349471_513f2ba5fdc9f0358700d72c_Berlin.JPG
  inflating: /content/__MACOSX/images/._52.538137_13.349471_513f2ba5fdc9f0358700d72c_Berlin.JPG
  inflating: /content/images/40.463598_-3.571007_514091acfdc9f04926000564_Madrid.JPG
  inflating: /content/__MACOSX/images/._40.463598_-3.571007_514091acfdc9f04926000564_Madrid.JPG
  inflating: /content/images/50.452376_30.458341_513e5c22fdc9f0358700aa38_Kiev.JPG
  inflating: /content/__MACOSX/images/._50.452376_30.458341_513e5c22fdc9f0358700aa38_Kiev.JPG
  inflating: /content/images/55.834083_-4.346699_51413503fdc9f0492600487b_Glasgow.JPG
  inflating: /content/__MACOSX/images/._55.834083_-4.346699_51413503fdc9f0492600487b_Glasgow.JPG
  inflating: /content/images/45.575593_-122.545294_50f60b8dbeb2fed910000062_Portland.JPG
  inflating: /content/__MACOSX/images/._45.575593_-122.545294_50f60b8dbeb2fed910000062_Portland.JPG
  inflating: /content/images/50.056870_14.348859_50f5eeacfdc9f065f0008fa0_Prague.JPG
  inflating: /content/__MACOSX/images/._50.056870_14.348859_50f5eeacfdc9f065f0008fa0_Prague.JPG
  inflating: /content/images/41.275444_2.004231_513d515cfdc9f03587002ec9_Barcelona.JPG
  inflating: /content/__MACOSX/images/._41.275444_2.004231_513d515cfdc9f03587002ec9_Barcelona.JPG
  inflating: /content/images/29.860033_-95.402387_513cbfa6fdc9f035870012d2_Houston.JPG
  inflating: /content/__MACOSX/images/._29.860033_-95.402387_513cbfa6fdc9f035870012d2_Houston.JPG
  inflating: /content/images/35.794079_139.732108_513e6abafdc9f0358700bf33_Tokyo.JPG
  inflating: /content/__MACOSX/images/._35.794079_139.732108_513e6abafdc9f0358700bf33_Tokyo.JPG
  inflating: /content/images/52.360358_4.859413_513d57e9fdc9f0358700324c_Amsterdam.JPG
  inflating: /content/__MACOSX/images/._52.360358_4.859413_513d57e9fdc9f0358700324c_Amsterdam.JPG
  inflating: /content/images/52.264518_21.154456_50f42c7efdc9f065f0001d75_Warsaw.JPG
  inflating: /content/__MACOSX/images/._52.264518_21.154456_50f42c7efdc9f065f0001d75_Warsaw.JPG
  inflating: /content/images/38.816211_-9.131960_51409212fdc9f04926000637_Lisbon.JPG
  inflating: /content/__MACOSX/images/._38.816211_-9.131960_51409212fdc9f04926000637_Lisbon.JPG
  inflating: /content/images/45.626907_-73.608102_5185d41bfdc9f03fd500137d_Montreal.JPG
  inflating: /content/__MACOSX/images/._45.626907_-73.608102_5185d41bfdc9f03fd500137d_Montreal.JPG
  inflating: /content/images/-23.468333_-46.594828_50f5e63cfdc9f065f0006b6f_SaoPaulo.JPG
  inflating: /content/__MACOSX/images/._-23.468333_-46.594828_50f5e63cfdc9f065f0006b6f_SaoPaulo.JPG
  inflating: /content/images/35.012651_135.770412_513e6418fdc9f0358700b7a3_Kyoto.JPG
  inflating: /content/__MACOSX/images/._35.012651_135.770412_513e6418fdc9f0358700b7a3_Kyoto.JPG
  inflating: /content/images/45.554265_-73.610692_5185d152fdc9f03fd50010d5_Montreal.JPG
  inflating: /content/__MACOSX/images/._45.554265_-73.610692_5185d152fdc9f03fd50010d5_Montreal.JPG
  inflating: /content/images/48.888888_2.220864_513e5f0efdc9f0358700b1b3_Paris.JPG
  inflating: /content/__MACOSX/images/._48.888888_2.220864_513e5f0efdc9f0358700b1b3_Paris.JPG
  inflating: /content/images/52.232199_21.156677_50f42bb4fdc9f065f000163b_Warsaw.JPG
  inflating: /content/__MACOSX/images/._52.232199_21.156677_50f42bb4fdc9f065f000163b_Warsaw.JPG
  inflating: /content/images/-33.956956_151.055857_50f44803fdc9f065f0003c30_Sydney.JPG
  inflating: /content/__MACOSX/images/._-33.956956_151.055857_50f44803fdc9f065f0003c30_Sydney.JPG
  inflating: /content/images/24.997477_121.558330_50f43b76fdc9f065f0003140_Taipei.JPG
  inflating: /content/__MACOSX/images/._24.997477_121.558330_50f43b76fdc9f065f0003140_Taipei.JPG
  inflating: /content/images/13.754441_100.579018_5140cad4fdc9f0492600296b_Bangkok.JPG
  inflating: /content/__MACOSX/images/._13.754441_100.579018_5140cad4fdc9f0492600296b_Bangkok.JPG
  inflating: /content/images/50.095149_14.363129_50f5ed58fdc9f065f0008c60_Prague.JPG
  inflating: /content/__MACOSX/images/._50.095149_14.363129_50f5ed58fdc9f065f0008c60_Prague.JPG
  inflating: /content/images/20.713611_-103.323908_514134ebfdc9f04926004823_Guadalajara.JPG
  inflating: /content/__MACOSX/images/._20.713611_-103.323908_514134ebfdc9f04926004823_Guadalajara.JPG
  inflating: /content/images/41.803349_12.510727_51409ce9fdc9f04926001253_Rome.JPG
  inflating: /content/__MACOSX/images/._41.803349_12.510727_51409ce9fdc9f04926001253_Rome.JPG
  inflating: /content/images/40.624196_-73.951235_513d9a74fdc9f035870076d2_NewYork.JPG
  inflating: /content/__MACOSX/images/._40.624196_-73.951235_513d9a74fdc9f035870076d2_NewYork.JPG
  inflating: /content/images/41.904253_-87.777871_513d2d8cfdc9f035870024f3_Chicago.JPG
  inflating: /content/__MACOSX/images/._41.904253_-87.777871_513d2d8cfdc9f035870024f3_Chicago.JPG
  inflating: /content/images/-33.825387_151.181051_50f44814fdc9f065f0003df1_Sydney.JPG
  inflating: /content/__MACOSX/images/._-33.825387_151.181051_50f44814fdc9f065f0003df1_Sydney.JPG
  inflating: /content/images/45.426267_-73.596293_5185cc32fdc9f03fd5000bf2_Montreal.JPG
  inflating: /content/__MACOSX/images/._45.426267_-73.596293_5185cc32fdc9f03fd5000bf2_Montreal.JPG
  inflating: /content/images/-34.044587_18.448401_513ce9d5fdc9f0358700231f_CapeTown.JPG
  inflating: /content/__MACOSX/images/._-34.044587_18.448401_513ce9d5fdc9f0358700231f_CapeTown.JPG
  inflating: /content/images/-33.896044_151.122453_50f44867fdc9f065f0003ff1_Sydney.JPG
  inflating: /content/__MACOSX/images/._-33.896044_151.122453_50f44867fdc9f065f0003ff1_Sydney.JPG
  inflating: /content/images/-33.510855_-70.589648_513d9b9efdc9f03587007a84_Santiago.JPG
  inflating: /content/__MACOSX/images/._-33.510855_-70.589648_513d9b9efdc9f03587007a84_Santiago.JPG
  inflating: /content/images/40.417190_-3.786751_5140907dfdc9f049260002e8_Madrid.JPG
  inflating: /content/__MACOSX/images/._40.417190_-3.786751_5140907dfdc9f049260002e8_Madrid.JPG
  inflating: /content/images/-23.537275_-46.646567_50f5e70afdc9f065f0006ff0_SaoPaulo.JPG
  inflating: /content/__MACOSX/images/._-23.537275_-46.646567_50f5e70afdc9f065f0006ff0_SaoPaulo.JPG
  inflating: /content/images/19.422210_-99.123019_51415108fdc9f04926007ebd_MexicoCity.JPG
  inflating: /content/__MACOSX/images/._19.422210_-99.123019_51415108fdc9f04926007ebd_MexicoCity.JPG
  inflating: /content/images/60.205269_24.841790_514133e2fdc9f04926004474_Helsinki.JPG
  inflating: /content/__MACOSX/images/._60.205269_24.841790_514133e2fdc9f04926004474_Helsinki.JPG
  inflating: /content/images/-22.844976_-43.321993_50f5eb6cfdc9f065f0008302_RioDeJaneiro.JPG
  inflating: /content/__MACOSX/images/._-22.844976_-43.321993_50f5eb6cfdc9f065f0008302_RioDeJaneiro.JPG
  inflating: /content/images/-33.889437_151.214608_50f46454fdc9f065f00045a9_Sydney.JPG
  inflating: /content/__MACOSX/images/._-33.889437_151.214608_50f46454fdc9f065f00045a9_Sydney.JPG
  inflating: /content/images/45.418395_9.277567_51415035fdc9f04926007cb1_Milan.JPG
  inflating: /content/__MACOSX/images/._45.418395_9.277567_51415035fdc9f04926007cb1_Milan.JPG
  inflating: /content/images/38.926855_-77.066384_5140b783fdc9f04926001a0d_WashingtonDC.JPG
  inflating: /content/__MACOSX/images/._38.926855_-77.066384_5140b783fdc9f04926001a0d_WashingtonDC.JPG
  inflating: /content/images/33.770409_-84.254518_513d9fedfdc9f0358700885b_Atlanta.JPG
  inflating: /content/__MACOSX/images/._33.770409_-84.254518_513d9fedfdc9f0358700885b_Atlanta.JPG
  inflating: /content/images/-22.797397_-43.371114_50f5ebaafdc9f065f000843b_RioDeJaneiro.JPG
  inflating: /content/__MACOSX/images/._-22.797397_-43.371114_50f5ebaafdc9f065f000843b_RioDeJaneiro.JPG
  inflating: /content/images/59.382274_18.002633_50f55e97fdc9f065f0004d41_Stockholm.JPG
  inflating: /content/__MACOSX/images/._59.382274_18.002633_50f55e97fdc9f065f0004d41_Stockholm.JPG
  inflating: /content/images/38.799475_-9.165638_51408b28fdc9f0358700e890_Lisbon.JPG
  inflating: /content/__MACOSX/images/._38.799475_-9.165638_51408b28fdc9f0358700e890_Lisbon.JPG
  inflating: /content/images/43.660292_-79.625979_50f4349dfdc9f065f0002a76_Toronto.JPG
  inflating: /content/__MACOSX/images/._43.660292_-79.625979_50f4349dfdc9f065f0002a76_Toronto.JPG
  inflating: /content/images/33.709118_-84.316255_513d9cd9fdc9f03587007e9b_Atlanta.JPG
  inflating: /content/__MACOSX/images/._33.709118_-84.316255_513d9cd9fdc9f03587007e9b_Atlanta.JPG
  inflating: /content/images/39.756443_-104.867123_513d6de3fdc9f03587005212_Denver.JPG
  inflating: /content/__MACOSX/images/._39.756443_-104.867123_513d6de3fdc9f03587005212_Denver.JPG
  inflating: /content/images/37.725065_-122.441008_50f5e8e1fdc9f065f000757a_SanFrancisco.JPG
  inflating: /content/__MACOSX/images/._37.725065_-122.441008_50f5e8e1fdc9f065f000757a_SanFrancisco.JPG
  inflating: /content/images/-33.546848_-70.587578_513d7b76fdc9f03587006b91_Santiago.JPG
  inflating: /content/__MACOSX/images/._-33.546848_-70.587578_513d7b76fdc9f03587006b91_Santiago.JPG
  inflating: /content/images/41.889881_12.425326_51409862fdc9f04926000c94_Rome.JPG
  inflating: /content/__MACOSX/images/._41.889881_12.425326_51409862fdc9f04926000c94_Rome.JPG
  inflating: /content/images/41.778766_-87.742204_513d33e2fdc9f035870029bb_Chicago.JPG
  inflating: /content/__MACOSX/images/._41.778766_-87.742204_513d33e2fdc9f035870029bb_Chicago.JPG
  inflating: /content/images/34.031049_-118.322414_514138fefdc9f04926005360_LosAngeles.JPG
  inflating: /content/__MACOSX/images/._34.031049_-118.322414_514138fefdc9f04926005360_LosAngeles.JPG
  inflating: /content/images/1.378444_103.878208_50f56060fdc9f065f0005169_Singapore.JPG
  inflating: /content/__MACOSX/images/._1.378444_103.878208_50f56060fdc9f065f0005169_Singapore.JPG
  inflating: /content/images/34.003683_-118.322384_51413a7dfdc9f0492600570e_LosAngeles.JPG
  inflating: /content/__MACOSX/images/._34.003683_-118.322384_51413a7dfdc9f0492600570e_LosAngeles.JPG
  inflating: /content/images/-22.922685_-43.232886_50f5eb6efdc9f065f0008329_RioDeJaneiro.JPG
  inflating: /content/__MACOSX/images/._-22.922685_-43.232886_50f5eb6efdc9f065f0008329_RioDeJaneiro.JPG
  inflating: /content/images/55.853473_-4.154653_5141333afdc9f04926004228_Glasgow.JPG
  inflating: /content/__MACOSX/images/._55.853473_-4.154653_5141333afdc9f04926004228_Glasgow.JPG
  inflating: /content/images/-22.883301_-43.296678_50f5eb17fdc9f065f0007f59_RioDeJaneiro.JPG
  inflating: /content/__MACOSX/images/._-22.883301_-43.296678_50f5eb17fdc9f065f0007f59_RioDeJaneiro.JPG
  inflating: /content/images/-19.887702_-43.918691_513d5d95fdc9f03587003907_BeloHorizonte.JPG
  inflating: /content/__MACOSX/images/._-19.887702_-43.918691_513d5d95fdc9f03587003907_BeloHorizonte.JPG
  inflating: /content/images/-33.936142_151.055305_50f46447fdc9f065f00044cd_Sydney.JPG
  inflating: /content/__MACOSX/images/._-33.936142_151.055305_50f46447fdc9f065f00044cd_Sydney.JPG
  inflating: /content/images/32.084092_34.773030_50f43aadfdc9f065f0002efc_TelAviv.JPG
  inflating: /content/__MACOSX/images/._32.084092_34.773030_50f43aadfdc9f065f0002efc_TelAviv.JPG
  inflating: /content/images/20.668530_-103.384720_51413388fdc9f04926004332_Guadalajara.JPG
  inflating: /content/__MACOSX/images/._20.668530_-103.384720_51413388fdc9f04926004332_Guadalajara.JPG
  inflating: /content/images/37.732702_-122.378594_50f5e880fdc9f065f000735c_SanFrancisco.JPG
  inflating: /content/__MACOSX/images/._37.732702_-122.378594_50f5e880fdc9f065f000735c_SanFrancisco.JPG
  inflating: /content/images/43.688446_-79.265501_50f463b9fdc9f065f00042bb_Toronto.JPG
  inflating: /content/__MACOSX/images/._43.688446_-79.265501_50f463b9fdc9f065f00042bb_Toronto.JPG
  inflating: /content/images/47.693345_-122.391823_50f563b6fdc9f065f0005e14_Seattle.JPG
  inflating: /content/__MACOSX/images/._47.693345_-122.391823_50f563b6fdc9f065f0005e14_Seattle.JPG
  inflating: /content/images/-23.604561_-46.690467_50f5e760fdc9f065f00070d1_SaoPaulo.JPG
  inflating: /content/__MACOSX/images/._-23.604561_-46.690467_50f5e760fdc9f065f00070d1_SaoPaulo.JPG
  inflating: /content/images/13.772615_100.607201_5140cba6fdc9f04926002c02_Bangkok.JPG
  inflating: /content/__MACOSX/images/._13.772615_100.607201_5140cba6fdc9f04926002c02_Bangkok.JPG
  inflating: /content/images/51.563440_0.032791_513e1e9ffdc9f03587009cf4_London.JPG
  inflating: /content/__MACOSX/images/._51.563440_0.032791_513e1e9ffdc9f03587009cf4_London.JPG
  inflating: /content/images/44.948349_-93.273031_51414800fdc9f04926006bb5_Minneapolis.JPG
  inflating: /content/__MACOSX/images/._44.948349_-93.273031_51414800fdc9f04926006bb5_Minneapolis.JPG
  inflating: /content/images/-33.999556_18.478003_513cdf3dfdc9f0358700211c_CapeTown.JPG
  inflating: /content/__MACOSX/images/._-33.999556_18.478003_513cdf3dfdc9f0358700211c_CapeTown.JPG
  inflating: /content/images/33.678082_-84.397863_513d7afefdc9f035870069f1_Atlanta.JPG
  inflating: /content/__MACOSX/images/._33.678082_-84.397863_513d7afefdc9f035870069f1_Atlanta.JPG
  inflating: /content/images/51.530905_-0.261113_513e1bc3fdc9f03587009565_London.JPG
  inflating: /content/__MACOSX/images/._51.530905_-0.261113_513e1bc3fdc9f03587009565_London.JPG
  inflating: /content/images/-23.492643_-46.598583_50f5e6c9fdc9f065f0006e14_SaoPaulo.JPG
  inflating: /content/__MACOSX/images/._-23.492643_-46.598583_50f5e6c9fdc9f065f0006e14_SaoPaulo.JPG
  inflating: /content/images/41.773894_-87.634887_513d3834fdc9f03587002c40_Chicago.JPG
  inflating: /content/__MACOSX/images/._41.773894_-87.634887_513d3834fdc9f03587002c40_Chicago.JPG
  inflating: /content/images/52.595266_13.385836_513f329cfdc9f0358700e0ae_Berlin.JPG
  inflating: /content/__MACOSX/images/._52.595266_13.385836_513f329cfdc9f0358700e0ae_Berlin.JPG
  inflating: /content/images/37.761158_-122.461819_50f5e896fdc9f065f00073a0_SanFrancisco.JPG
  inflating: /content/__MACOSX/images/._37.761158_-122.461819_50f5e896fdc9f065f00073a0_SanFrancisco.JPG
  inflating: /content/images/43.696670_-79.370012_50f42eeffdc9f065f000240b_Toronto.JPG

In [ ]:
# Load votes
df_votes = pd.read_csv("/content/votes.tsv", sep="\t")

# Load studies
df_studies = pd.read_csv("/content/studies.tsv", sep="\t")

# Image directory
image_dir = "/content/images"

In [ ]:
print(df_votes.shape)
print(df_studies.shape)
print(len(os.listdir(image_dir)))

(1555561, 7)
(6, 6)
110988

In [ ]:
df_votes["choice"].value_counts()

choice
right                                       686368
left                                        664178
equal                                       204992
rigPr                                            5
equPr                                            5
lePr                                             4
response.write(9854781*9182327)                  1
set|set&set                                      1
'+response.write(9854781*9182327)+'              1
tbFr9gKC                                         1
../../../../../../../../../../etc/passwd         1
$(nslookup ErfMv0bx)                             1
${10000266+9999972}                              1
+response.write(9854781*9182327)+                1
Name: count, dtype: int64

In [ ]:
df_votes = df_votes[df_votes["choice"].isin(["left", "right"])]
print(df_votes["choice"].value_counts())

choice
right    686368
left     664178
Name: count, dtype: int64

In [ ]:
# ==========================================
# Build Pair-Level Dataset
# ==========================================

# Create pair identifier
df_votes["pair_id"] = df_votes.apply(
    lambda x: "_".join(
        sorted([str(x["left"]), str(x["right"])])
    ) + "_" + str(x["study_id"]),
    axis=1
)

# Count left wins
left_votes = (
    df_votes[df_votes["choice"].isin(["left", "A", 0])]
    .groupby(["pair_id", "left", "right", "study_id"])
    .size()
    .reset_index(name="left_votes")
)

# Count right wins
right_votes = (
    df_votes[df_votes["choice"].isin(["right", "B", 1])]
    .groupby(["pair_id", "left", "right", "study_id"])
    .size()
    .reset_index(name="right_votes")
)

# Merge vote counts
pair_df = pd.merge(
    left_votes,
    right_votes,
    on=["pair_id", "left", "right", "study_id"],
    how="outer"
)

pair_df["left_votes"] = pair_df["left_votes"].fillna(0)
pair_df["right_votes"] = pair_df["right_votes"].fillna(0)

print("Pairs before filtering:", len(pair_df))
pair_df.head()

Pairs before filtering: 1333630

,pair_id,left,right,study_id,left_votes,right_votes
0,${9999640+9999388}_5140d960fdc9f04926003bb4_50...,${9999640+9999388},5140d960fdc9f04926003bb4,50f62c41a84ea7c5fdd2e454,1.0,0.0
1,50e5f7d4d7c3df413b00056a_50f42c0dfdc9f065f0001...,50e5f7d4d7c3df413b00056a,50f42c0dfdc9f065f00017bc,50a68a51fdc9f05596000002,1.0,0.0
2,50e5f7d4d7c3df413b00056a_50f42c6afdc9f065f0001...,50f42c6afdc9f065f0001bd4,50e5f7d4d7c3df413b00056a,50a68a51fdc9f05596000002,1.0,0.0
3,50e5f7d4d7c3df413b00056a_50f55e9afdc9f065f0004...,50f55e9afdc9f065f0004d7b,50e5f7d4d7c3df413b00056a,50f62c68a84ea7c5fdd2e456,1.0,0.0
4,50e5f7d4d7c3df413b00056a_50f562ddfdc9f065f0005...,50e5f7d4d7c3df413b00056a,50f562ddfdc9f065f0005af3,50a68a51fdc9f05596000002,0.0,1.0

In [ ]:
pair_df["total_votes"] = pair_df["left_votes"] + pair_df["right_votes"]

pair_df["winner"] = pair_df.apply(
    lambda x: "left" if x["left_votes"] > x["right_votes"]
    else ("right" if x["right_votes"] > x["left_votes"] else "tie"),
    axis=1
)

pair_df["winner"].value_counts()

winner
right    677407
left     655829
tie         394
Name: count, dtype: int64

In [ ]:
pair_df = pair_df[pair_df["winner"] != "tie"]

print("Pairs after removing ties:", len(pair_df))

Pairs after removing ties: 1333236

In [ ]:
pair_df["majority_ratio"] = pair_df.apply(
    lambda x: max(x["left_votes"], x["right_votes"]) / x["total_votes"],
    axis=1
)

pair_df = pair_df[pair_df["majority_ratio"] >= 0.7].copy()

print("Final clean pairs:", len(pair_df))

Final clean pairs: 1332944

In [ ]:
print("Total pairs:", len(pair_df))

print("Average votes per pair:",
      pair_df["total_votes"].mean())

print("Tie percentage:",
      (pair_df["winner"] == "tie").mean())

Total pairs: 1332944
Average votes per pair: 1.0112675401217155
Tie percentage: 0.0

In [ ]:
df_votes["left_norm"] = df_votes[["left","right"]].min(axis=1)
df_votes["right_norm"] = df_votes[["left","right"]].max(axis=1)

In [ ]:
pair_counts = df_votes.groupby(["left_norm", "right_norm", "study_id"]).size()

print("Pairs with more than one vote:",
      (pair_counts > 1).sum())

print("Max votes for a single pair:",
      pair_counts.max())

Pairs with more than one vote: 5618
Max votes for a single pair: 69

In [ ]:
pair_votes = (
    df_votes.groupby(["left_norm", "right_norm", "study_id", "choice"])
    .size()
    .unstack(fill_value=0)
)

print("Vote columns:", pair_votes.columns)

# Get the two vote columns dynamically
col1, col2 = pair_votes.columns[:2]

pair_votes["tie"] = pair_votes[col1] == pair_votes[col2]

print("True tie pairs:", pair_votes["tie"].sum())

Vote columns: Index(['left', 'right'], dtype='object', name='choice')
True tie pairs: 405

In [ ]:
image_map = {}

for file in os.listdir(image_dir):
    if file.lower().endswith(".jpg"):
        parts = file.split("_")
        if len(parts) >= 3:
            image_id = parts[2]  # <-- THIS is the correct ID
            image_map[image_id] = os.path.join(image_dir, file)

print("Total images mapped:", len(image_map))

Total images mapped: 110988

In [ ]:
print(len(image_map))

110988

In [ ]:
print("Total cleaned votes:", len(df_votes))

print("Unique pairs:",
      df_votes.groupby(["left","right","study_id"]).ngroups)

print("Average votes per pair:",
      df_votes.groupby(["left","right","study_id"]).size().mean())

Total cleaned votes: 1350546
Unique pairs: 1333630
Average votes per pair: 1.012684177770446

In [ ]:
model_id = "llava-hf/llava-1.5-7b-hf"

processor = LlavaProcessor.from_pretrained(model_id)

model = LlavaForConditionalGeneration.from_pretrained(
    model_id,
    torch_dtype=torch.float16,
    low_cpu_mem_usage=True
).to("cuda")

print("Model loaded.")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

processor_config.json:   0%|          | 0.00/173 [00:00<?, ?B/s]

chat_template.json:   0%|          | 0.00/701 [00:00<?, ?B/s]

chat_template.jinja:   0%|          | 0.00/674 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

preprocessor_config.json:   0%|          | 0.00/505 [00:00<?, ?B/s]

The image processor of type `CLIPImageProcessor` is now loaded as a fast processor by default, even if the model checkpoint was saved with a slow processor. This is a breaking change and may produce slightly different outputs. To continue using the slow processor, instantiate this class with `use_fast=False`.

config.json:   0%|          | 0.00/950 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

tokenizer.model:   0%|          | 0.00/500k [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/41.0 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/552 [00:00<?, ?B/s]

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 3 files:   0%|          | 0/3 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/686 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/141 [00:00<?, ?B/s]

Model loaded.

In [ ]:
def concatenate_images(path_A, path_B):
    img_A = Image.open(path_A).convert("RGB")
    img_B = Image.open(path_B).convert("RGB")

    new_img = Image.new("RGB", (img_A.width + img_B.width, img_A.height))
    new_img.paste(img_A, (0, 0))
    new_img.paste(img_B, (img_A.width, 0))

    return new_img

In [ ]:
ATTRIBUTE_CUES = {
    "beautiful": [
        "architecture",
        "greenery",
        "cleanliness",
        "visual harmony",
        "scenic features"
    ],
    "safer": [
    "well-lit areas",
    "visible people nearby",
    "clean and maintained streets",
    "no signs of damage or neglect",
    "active businesses or shops"
],
    "wealthier": [
        "modern buildings",
        "expensive cars",
        "clean streets",
        "landscaping",
        "well maintained infrastructure"
    ],
    "livelier": [
       "many people visible",
        "movement or activity",
        "vehicles or pedestrians",
        "open shops or markets",
        "bright lights or signs"
    ],
    "more boring": [
        "plain buildings",
        "empty streets",
        "lack of activity",
        "few people",
        "dull environment"
    ],
    "more depressing": [
        "abandoned buildings",
        "poor lighting",
        "empty streets",
        "graffiti",
        "neglected infrastructure"
    ]
}

In [ ]:
attribute_map = {
    "beautiful": "5217c351ad93a7d3e7b07a64",
    "safer": "50a68a51fdc9f05596000002",
    "livelier": "50f62c41a84ea7c5fdd2e454",
    "more boring": "50f62c68a84ea7c5fdd2e456",
    "wealthier": "50f62cb7a84ea7c5fdd2e458",
    "more depressing": "50f62ccfa84ea7c5fdd2e459",

}

In [ ]:
def get_prediction(image1, image2, attribute):

    prompt = f"""
    Image A and Image B are shown.

    Compare the two images carefully.

    Which image looks more {attribute}?

    Answer with only A or B.
    """

    combined = concatenate_images(image1, image2)

    inputs = processor(
        images=combined,
        text=prompt,
        return_tensors="pt"
    ).to(model.device)

    output = model.generate(**inputs, max_new_tokens=10)

    answer = processor.decode(output[0], skip_special_tokens=True)

    return answer

In [ ]:
def evaluate_attribute(attribute_name, study_id, n_samples=50):

    votes = df_votes[df_votes["study_id"] == study_id].copy()
    print(f"{attribute_name} — votes after study filter:", len(votes))

    votes = votes[
        votes["left"].isin(image_map.keys()) &
        votes["right"].isin(image_map.keys())
    ].copy()

    print(f"{attribute_name} — votes after image filter:", len(votes))

    records = []

    for _, row in votes.iterrows():
        img_A = image_map[row["left"]]
        img_B = image_map[row["right"]]
        label = 1 if row["choice"] == "left" else 0

        records.append({
            "img_A": img_A,
            "img_B": img_B,
            "label": label
        })

    votes_df = pd.DataFrame(records)

    if len(votes_df) < n_samples:
        n_samples = len(votes_df)

    eval_df = votes_df.sample(n=n_samples, random_state=42).reset_index(drop=True)

    print("votes_df length:", len(votes_df))
    print("eval_df length:", len(eval_df))

    ########################################
    # ✅ FINAL PARSER (SUPPORTS BOTH MODES)
    ########################################

    def parse_prediction(text):
        if text is None:
            return None

        text = text.lower().strip()

        if "assistant:" in text:
            text = text.split("assistant:")[-1].strip()

        # CoT format
        if "answer: a" in text:
            return 1
        if "answer: b" in text:
            return 0

        # Direct format
        if "image a" in text:
            return 1
        if "image b" in text:
            return 0

        # Fallback
        if text == "a" or text.startswith("a"):
            return 1
        if text == "b" or text.startswith("b"):
            return 0

        return None

    ########################################
    # DIRECT
    ########################################

    direct_results = []

    for i in tqdm(range(len(eval_df)), desc=f"Direct: {attribute_name}"):

        img_A = eval_df.iloc[i]["img_A"]
        img_B = eval_df.iloc[i]["img_B"]
        gt = eval_df.iloc[i]["label"]

        prompt = f"""USER: <image>
Which place looks {attribute_name}?

Answer ONLY with:
Image A
or
Image B
ASSISTANT:"""

        combined_img = concatenate_images(img_A, img_B)

        inputs = processor(text=prompt, images=combined_img, return_tensors="pt").to("cuda", torch.float16)
        output = model.generate(**inputs, max_new_tokens=5, temperature=0.0, do_sample=False)
        pred1 = parse_prediction(processor.decode(output[0], skip_special_tokens=True))

        combined_img_swapped = concatenate_images(img_B, img_A)

        inputs = processor(text=prompt, images=combined_img_swapped, return_tensors="pt").to("cuda", torch.float16)
        output = model.generate(**inputs, max_new_tokens=5, temperature=0.0, do_sample=False)
        pred2 = parse_prediction(processor.decode(output[0], skip_special_tokens=True))

        if pred2 is not None:
            pred2 = 1 - pred2

        is_tie = (pred1 is not None and pred2 is not None and pred1 != pred2)

        votes = [v for v in [pred1, pred2] if v is not None]

        if len(votes) == 0:
            final_pred = None
        elif votes.count(1) > votes.count(0):
            final_pred = 1
        elif votes.count(0) > votes.count(1):
            final_pred = 0
        else:
            final_pred = pred1

        direct_results.append({"pred": final_pred, "gt": gt, "tie": is_tie})

    ########################################
    # CoT (FIXED)
    ########################################

    cot_results = []

    for i in tqdm(range(len(eval_df)), desc=f"CoT: {attribute_name}"):

        img_A = eval_df.iloc[i]["img_A"]
        img_B = eval_df.iloc[i]["img_B"]
        gt = eval_df.iloc[i]["label"]

        cues = ATTRIBUTE_CUES.get(attribute_name.lower(), [])
        cue_text = ", ".join(cues)

        reasoning_prompt = f"""USER: <image>

Two places are shown side-by-side:

Image A (left)
Image B (right)

Your task is to determine which place looks more **{attribute_name}**.

Important visual cues related to "{attribute_name}" may include:
{cue_text}

Follow these steps:

Step 1: Briefly describe Image A focusing on relevant cues.
Step 2: Briefly describe Image B focusing on relevant cues.
Step 3: Compare both images based on those cues.
Step 4: Decide which image better represents "{attribute_name}".

IMPORTANT:
Give your final answer EXACTLY in this format on a new line:
Answer: A
or
Answer: B

ASSISTANT:
"""

        combined_img = concatenate_images(img_A, img_B)

        inputs = processor(text=reasoning_prompt, images=combined_img, return_tensors="pt").to("cuda", torch.float16)

        output = model.generate(
            **inputs,
            max_new_tokens=80,
            temperature=0.0,
            do_sample=False
        )

        pred1 = parse_prediction(processor.decode(output[0], skip_special_tokens=True))

        # SWAPPED
        combined_img_swapped = concatenate_images(img_B, img_A)

        inputs = processor(text=reasoning_prompt, images=combined_img_swapped, return_tensors="pt").to("cuda", torch.float16)

        output = model.generate(
            **inputs,
            max_new_tokens=80,
            temperature=0.0,
            do_sample=False
        )

        pred2 = parse_prediction(processor.decode(output[0], skip_special_tokens=True))

        if pred2 is not None:
            pred2 = 1 - pred2

        is_tie = (pred1 is not None and pred2 is not None and pred1 != pred2)

        votes = [v for v in [pred1, pred2] if v is not None]

        if len(votes) == 0:
            final_pred = None
        elif votes.count(1) > votes.count(0):
            final_pred = 1
        elif votes.count(0) > votes.count(1):
            final_pred = 0
        else:
            final_pred = pred1

        cot_results.append({"pred": final_pred, "gt": gt, "tie": is_tie})

    ########################################
    # METRICS
    ########################################

    def compute_metrics(results):
        total = sum(r["pred"] is not None for r in results)
        correct = sum(r["pred"] == r["gt"] for r in results if r["pred"] is not None)

        acc = correct / total if total > 0 else 0
        tie_rate = sum(r["tie"] for r in results) / len(results)

        return acc, tie_rate

    direct_acc, direct_tie = compute_metrics(direct_results)
    cot_acc, cot_tie = compute_metrics(cot_results)

    ########################################
    # DEBUG
    ########################################

    print("Direct valid predictions:", sum(r["pred"] is not None for r in direct_results))
    print("CoT valid predictions:", sum(r["pred"] is not None for r in cot_results))
    print("Total samples:", len(eval_df))

    ########################################
    # RETURN
    ########################################

    return {
        "attribute": attribute_name,
        "direct_acc": direct_acc,
        "cot_acc": cot_acc,
        "direct_tie_rate": direct_tie,
        "cot_tie_rate": cot_tie
    }

In [ ]:
attributes = [
    "beautiful",
    "safer",
    "livelier",
    "more boring",
    "wealthier",
    "more depressing",

]

In [ ]:
evaluate_attribute("livelier", attribute_map["livelier"], n_samples=100)

livelier — votes after study filter: 320803
livelier — votes after image filter: 318958
votes_df length: 318958
eval_df length: 100

Direct: livelier:   0%|          | 0/100 [00:00<?, ?it/s]The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Direct: livelier: 100%|██████████| 100/100 [00:32<00:00,  3.06it/s]
CoT: livelier: 100%|██████████| 100/100 [00:42<00:00,  2.34it/s]

Direct valid predictions: 100
CoT valid predictions: 100
Total samples: 100

{'attribute': 'livelier',
 'direct_acc': np.float64(0.45),
 'cot_acc': np.float64(0.59),
 'direct_tie_rate': 0.87,
 'cot_tie_rate': 0.69}

In [ ]:
evaluate_attribute("more depressing", attribute_map["more depressing"], n_samples=100)

more depressing — votes after study filter: 125030
more depressing — votes after image filter: 124257
votes_df length: 124257
eval_df length: 100

Direct: more depressing: 100%|██████████| 100/100 [00:30<00:00,  3.23it/s]
CoT: more depressing: 100%|██████████| 100/100 [00:44<00:00,  2.22it/s]

Direct valid predictions: 100
CoT valid predictions: 100
Total samples: 100

{'attribute': 'more depressing',
 'direct_acc': np.float64(0.54),
 'cot_acc': np.float64(0.5),
 'direct_tie_rate': 0.37,
 'cot_tie_rate': 0.4}

In [ ]:
results = []

for attr in attributes:

    print("\n==============================")
    print(f"Running evaluation for: {attr}")
    print("==============================\n")

    res = evaluate_attribute(attr, attribute_map[attr], n_samples=100)


    results.append(res)

==============================
Running evaluation for: beautiful
==============================

beautiful — votes after study filter: 190606
beautiful — votes after image filter: 189539

KeyboardInterrupt:

In [ ]:
results_df = pd.DataFrame(results)
print(results_df)

         attribute  direct_acc  cot_acc  direct_tie_rate  cot_tie_rate
0        beautiful        0.65     0.59             0.39          0.51
1            safer        0.56     0.54             0.77          0.42
2         livelier        0.45     0.59             0.87          0.69
3      more boring        0.51     0.51             0.98          0.61
4        wealthier        0.54     0.54             0.55          0.46
5  more depressing        0.54     0.50             0.37          0.40

In [ ]:
print("Sample vote left ID:", df_votes["left"].iloc[0])
print("Sample image_map key:", list(image_map.keys())[0])

Sample vote left ID: 513d2dbefdc9f03587002515
Sample image_map key: 5141471efdc9f049260069a4

In [ ]:
# ==========================================
# Independent Scoring Evaluation
# ==========================================
def get_score(image_path, attribute_name):

    image = Image.open(image_path).convert("RGB")

    prompt = f"""USER: <image>
On a scale from 0 to 10,
how {attribute_name.rstrip('r')} does this place look?

Answer ONLY with a number between 0 and 10.
ASSISTANT:"""

    inputs = processor(
        text=prompt,
        images=image,
        return_tensors="pt"
    ).to("cuda", torch.float16)

    output = model.generate(
        **inputs,
        max_new_tokens=10,
        temperature=0.0,
        do_sample=False
    )

    full_text = processor.decode(output[0], skip_special_tokens=True)

# Only keep text after ASSISTANT:
    if "ASSISTANT:" in full_text:
      text = full_text.split("ASSISTANT:")[-1].strip()
    else:
      text = full_text.strip()
    print("RAW OUTPUT:", text)  # ← add this

    import re

    numbers = re.findall(r"\d+", text)

    if numbers:
      return int(numbers[0])   # now first number is correct
    else:
      return 0

In [ ]:
def evaluate_attribute_independent(attribute_name, study_id, n_samples=100):

    ATTRIBUTE_PHRASES = {
        "beautiful":       "beautiful",
        "safer":           "safe",
        "wealthier":       "wealthy",
        "livelier":        "lively",
        "more boring":     "boring",
        "more depressing": "depressing"
    }

    votes = df_votes[df_votes["study_id"] == study_id].copy()
    print(f"{attribute_name} — votes after study filter:", len(votes))

    votes = votes[
        votes["left"].isin(image_map.keys()) &
        votes["right"].isin(image_map.keys())
    ].copy()

    print(f"{attribute_name} — votes after image filter:", len(votes))

    records = []
    for _, row in votes.iterrows():
        img_A = image_map[row["left"]]
        img_B = image_map[row["right"]]
        label = 1 if row["choice"] == "left" else 0
        records.append({"img_A": img_A, "img_B": img_B, "label": label})

    votes_df = pd.DataFrame(records)

    if len(votes_df) < n_samples:
        n_samples = len(votes_df)

    eval_df = votes_df.sample(n=n_samples, random_state=42).reset_index(drop=True)

    print("votes_df length:", len(votes_df))
    print("eval_df length:", len(eval_df))

    def parse_score(text):
        text = text.lower().strip()
        if "assistant:" in text:
            text = text.split("assistant:")[-1].strip()
        import re
        match = re.search(r"\d+", text)
        return int(match.group()) if match else None

    results = []

    for i in tqdm(range(len(eval_df)), desc=f"Independent: {attribute_name}"):

        img_A = eval_df.iloc[i]["img_A"]
        img_B = eval_df.iloc[i]["img_B"]
        gt    = eval_df.iloc[i]["label"]

        cues        = ATTRIBUTE_CUES.get(attribute_name.lower(), [])
        cue_text    = ", ".join(cues)
        attr_phrase = ATTRIBUTE_PHRASES.get(attribute_name.lower(), attribute_name)

        # Original prompt — best results so far
        prompt = f"""USER: <image>

Rate how {attr_phrase} this place looks on a scale from 0 to 100.

Important visual cues may include:
{cue_text}

Be precise and use the full range when appropriate.
Avoid default or middle values unless necessary.
Use a wide range of scores to clearly distinguish between different scenes.
Do not give identical scores unless the two places truly look the same.

Answer ONLY with a number between 0 and 100.

ASSISTANT:"""

        scores = []
        for img_path in [img_A, img_B]:
            image  = Image.open(img_path).convert("RGB")
            inputs = processor(
                text=prompt,
                images=image,
                return_tensors="pt"
            ).to("cuda", torch.float16)

            output = model.generate(
                **inputs,
                max_new_tokens=10,
                temperature=0.0,
                do_sample=False
            )

            score = parse_score(
                processor.decode(output[0], skip_special_tokens=True)
            )
            scores.append(score)

        score_A, score_B = scores

        # Original threshold
        threshold = 3
        if attribute_name == "livelier":
            threshold = 1
        else:
            threshold = 3

        if score_A is None or score_B is None:
            final_pred, is_tie = None, False
        elif abs(score_A - score_B) <= threshold:
            final_pred, is_tie = None, True
        elif score_A > score_B:
            final_pred, is_tie = 1, False
        else:
            final_pred, is_tie = 0, False

        results.append({
            "pred":    final_pred,
            "gt":      gt,
            "tie":     is_tie,
            "score_A": score_A,
            "score_B": score_B
        })

    def compute_metrics(results):
        total    = sum(r["pred"] is not None for r in results)
        correct  = sum(r["pred"] == r["gt"] for r in results if r["pred"] is not None)
        acc      = correct / total if total > 0 else None
        pred_A   = sum(r["pred"] == 1 for r in results)
        pred_B   = sum(r["pred"] == 0 for r in results)
        tie_rate = sum(r["tie"] for r in results) / len(results) if results else 0
        return acc, pred_A, pred_B, tie_rate

    acc, pred_A, pred_B, tie_rate = compute_metrics(results)

    scores_A = [r["score_A"] for r in results if r["score_A"] is not None]
    scores_B = [r["score_B"] for r in results if r["score_B"] is not None]
    if scores_A and scores_B:
        print(f"Score A — min: {min(scores_A)}, max: {max(scores_A)}, mean: {sum(scores_A)/len(scores_A):.1f}")
        print(f"Score B — min: {min(scores_B)}, max: {max(scores_B)}, mean: {sum(scores_B)/len(scores_B):.1f}")

    return {
        "attribute":            attribute_name,
        "independent_acc":      round(acc, 3) if acc else None,
        "independent_A":        pred_A,
        "independent_B":        pred_B,
        "independent_tie_rate": round(tie_rate, 3)
    }

In [ ]:
evaluate_attribute_independent("beautiful", attribute_map["beautiful"], n_samples=100)

beautiful — votes after study filter: 190606
beautiful — votes after image filter: 189539
votes_df length: 189539
eval_df length: 100

Independent: beautiful: 100%|██████████| 100/100 [00:41<00:00,  2.44it/s]

Score A — min: 50, max: 90, mean: 79.3
Score B — min: 50, max: 90, mean: 81.0

{'attribute': 'beautiful',
 'independent_acc': np.float64(0.83),
 'independent_A': 22,
 'independent_B': 31,
 'independent_tie_rate': 0.47}

In [ ]:
results = []

for attr in attributes:

    print("\n==============================")
    print(f"Running evaluation for: {attr}")
    print("==============================\n")

    res = evaluate_attribute_independent(attr, attribute_map[attr], n_samples=100)

    results.append(res)



results_df = pd.DataFrame(results)

results_df = results_df[[
    "attribute",
    "independent_acc",
    "independent_tie_rate"
]].round(3)

results_df

==============================
Running evaluation for: beautiful
==============================

beautiful — votes after study filter: 190606
beautiful — votes after image filter: 189539
votes_df length: 189539
eval_df length: 100

Independent: beautiful: 100%|██████████| 100/100 [00:41<00:00,  2.40it/s]

Score A — min: 50, max: 90, mean: 79.3
Score B — min: 50, max: 90, mean: 81.0

==============================
Running evaluation for: safer
==============================

safer — votes after study filter: 443052
safer — votes after image filter: 440758
votes_df length: 440758
eval_df length: 100

Independent: safer: 100%|██████████| 100/100 [00:41<00:00,  2.42it/s]

Score A — min: 50, max: 100, mean: 76.7
Score B — min: 50, max: 100, mean: 77.0

==============================
Running evaluation for: livelier
==============================

livelier — votes after study filter: 320803
livelier — votes after image filter: 318958
votes_df length: 318958
eval_df length: 100

Independent: livelier: 100%|██████████| 100/100 [00:40<00:00,  2.45it/s]

Score A — min: 0, max: 70, mean: 49.9
Score B — min: 0, max: 70, mean: 48.7

==============================
Running evaluation for: more boring
==============================

more boring — votes after study filter: 120453
more boring — votes after image filter: 119681
votes_df length: 119681
eval_df length: 100

Independent: more boring: 100%|██████████| 100/100 [00:41<00:00,  2.40it/s]

Score A — min: 50, max: 90, mean: 68.0
Score B — min: 50, max: 100, mean: 64.5

==============================
Running evaluation for: wealthier
==============================

wealthier — votes after study filter: 150602
wealthier — votes after image filter: 149799
votes_df length: 149799
eval_df length: 100

Independent: wealthier: 100%|██████████| 100/100 [00:41<00:00,  2.40it/s]

Score A — min: 50, max: 100, mean: 64.2
Score B — min: 50, max: 100, mean: 63.2

==============================
Running evaluation for: more depressing
==============================

more depressing — votes after study filter: 125030
more depressing — votes after image filter: 124257
votes_df length: 124257
eval_df length: 100

Independent: more depressing: 100%|██████████| 100/100 [00:40<00:00,  2.46it/s]

Score A — min: 50, max: 80, mean: 58.9
Score B — min: 50, max: 90, mean: 58.9

         attribute  independent_acc  independent_tie_rate
0        beautiful            0.830                  0.47
1            safer            0.700                  0.50
2         livelier            0.714                  0.93
3      more boring            0.644                  0.41
4        wealthier            0.725                  0.31
5  more depressing            0.596                  0.48

In [ ]:
# Debug livelier with ASSISTANT: ending
attr_phrase = "lively"
cues        = ATTRIBUTE_CUES.get("livelier", [])
cue_text    = ", ".join(cues)

prompt = f"""USER: <image>

Rate how {attr_phrase} this place looks on a scale from 0 to 100.

Important visual cues may include:
{cue_text}

Be precise and use the full range when appropriate.
Avoid default or middle values unless necessary.
Use a wide range of scores to clearly distinguish between different scenes.
Do not give identical scores unless the two places truly look the same.

Answer ONLY with a number between 0 and 100.

ASSISTANT:"""

votes  = df_votes[df_votes["study_id"] == attribute_map["livelier"]].copy()
sample = votes[
    votes["left"].isin(image_map.keys()) &
    votes["right"].isin(image_map.keys())
].sample(5, random_state=42)

for _, row in sample.iterrows():
    for img_id, label in [(row["left"], "A"), (row["right"], "B")]:
        image  = Image.open(image_map[img_id]).convert("RGB")
        inputs = processor(
            text=prompt, images=image, return_tensors="pt"
        ).to("cuda", torch.float16)
        output = model.generate(
            **inputs, max_new_tokens=10, temperature=0.0, do_sample=False
        )
        raw   = processor.decode(output[0], skip_special_tokens=True)
        after = raw.split("ASSISTANT:")[-1].strip()
        print(f"Image {label} | Score: {after}")
    print("---")

Image A | Score: 50
Image B | Score: 50
---
Image A | Score: 50
Image B | Score: 50
---
Image A | Score: 50
Image B | Score: 50
---
Image A | Score: 50
Image B | Score: 50
---
Image A | Score: 50
Image B | Score: 50
---

In [ ]:
def evaluate_livelier_independent(study_id, n_samples=100):

    votes = df_votes[df_votes["study_id"] == study_id].copy()
    print(f"livelier — votes after study filter:", len(votes))

    votes = votes[
        votes["left"].isin(image_map.keys()) &
        votes["right"].isin(image_map.keys())
    ].copy()

    print(f"livelier — votes after image filter:", len(votes))

    records = []
    for _, row in votes.iterrows():
        img_A = image_map[row["left"]]
        img_B = image_map[row["right"]]
        label = 1 if row["choice"] == "left" else 0
        records.append({"img_A": img_A, "img_B": img_B, "label": label})

    votes_df = pd.DataFrame(records)
    eval_df  = votes_df.sample(n=min(n_samples, len(votes_df)), random_state=42).reset_index(drop=True)

    print("eval_df length:", len(eval_df))

    def parse_score(text):
        text = text.lower().strip()
        if "assistant:" in text:
            text = text.split("assistant:")[-1].strip()
        import re
        match = re.search(r"\d+", text)
        return int(match.group()) if match else None

    cues     = ATTRIBUTE_CUES.get("livelier", [])
    cue_text = ", ".join(cues)

    # Same prompt but with ASSISTANT: ending instead of A:
    prompt = f"""USER: <image>

Rate how lively this place looks on a scale from 0 to 100.

Important visual cues may include:
{cue_text}

Be precise and use the full range when appropriate.
Avoid default or middle values unless necessary.
Use a wide range of scores to clearly distinguish between different scenes.
Do not give identical scores unless the two places truly look the same.

Answer ONLY with a number between 0 and 100.

ASSISTANT:"""

    results = []

    for i in tqdm(range(len(eval_df)), desc="Independent: livelier"):

        img_A = eval_df.iloc[i]["img_A"]
        img_B = eval_df.iloc[i]["img_B"]
        gt    = eval_df.iloc[i]["label"]

        scores = []
        for img_path in [img_A, img_B]:
            image  = Image.open(img_path).convert("RGB")
            inputs = processor(
                text=prompt, images=image, return_tensors="pt"
            ).to("cuda", torch.float16)
            output = model.generate(
                **inputs, max_new_tokens=10, temperature=0.0, do_sample=False
            )
            score = parse_score(
                processor.decode(output[0], skip_special_tokens=True)
            )
            scores.append(score)

        score_A, score_B = scores

        THRESHOLD = 5  # Keep original threshold for livelier

        if score_A is None or score_B is None:
            final_pred, is_tie = None, False
        elif abs(score_A - score_B) <= THRESHOLD:
            final_pred, is_tie = None, True
        elif score_A > score_B:
            final_pred, is_tie = 1, False
        else:
            final_pred, is_tie = 0, False

        results.append({
            "pred":    final_pred,
            "gt":      gt,
            "tie":     is_tie,
            "score_A": score_A,
            "score_B": score_B
        })

    total    = sum(r["pred"] is not None for r in results)
    correct  = sum(r["pred"] == r["gt"] for r in results if r["pred"] is not None)
    acc      = correct / total if total > 0 else None
    tie_rate = sum(r["tie"] for r in results) / len(results) if results else 0

    scores_A = [r["score_A"] for r in results if r["score_A"] is not None]
    scores_B = [r["score_B"] for r in results if r["score_B"] is not None]
    if scores_A and scores_B:
        print(f"Score A — min: {min(scores_A)}, max: {max(scores_A)}, mean: {sum(scores_A)/len(scores_A):.1f}")
        print(f"Score B — min: {min(scores_B)}, max: {max(scores_B)}, mean: {sum(scores_B)/len(scores_B):.1f}")

    return {
        "attribute":            "livelier",
        "independent_acc":      round(acc, 3) if acc else None,
        "independent_tie_rate": round(tie_rate, 3)
    }

# Run it
res = evaluate_livelier_independent(attribute_map["livelier"], n_samples=100)
print("\n=== LIVELIER RESULTS ===")
print(res)

livelier — votes after study filter: 320803
livelier — votes after image filter: 318958
eval_df length: 100

Independent: livelier: 100%|██████████| 100/100 [00:41<00:00,  2.44it/s]

Score A — min: 0, max: 70, mean: 49.9
Score B — min: 0, max: 70, mean: 48.7

=== LIVELIER RESULTS ===
{'attribute': 'livelier', 'independent_acc': np.float64(0.714), 'independent_tie_rate': 0.93}

In [ ]:
cues     = ATTRIBUTE_CUES.get("livelier", [])
cue_text = ", ".join(cues)

prompt = f"""USER: <image>

Look at this street scene.

How lively does this place look?

Visual cues for liveliness: {cue_text}

Answer with ONLY one of these three options:
low
medium
high

A:"""

votes  = df_votes[df_votes["study_id"] == attribute_map["livelier"]].copy()
sample = votes[
    votes["left"].isin(image_map.keys()) &
    votes["right"].isin(image_map.keys())
].sample(5, random_state=42)

for _, row in sample.iterrows():
    for img_id, label in [(row["left"], "A"), (row["right"], "B")]:
        image  = Image.open(image_map[img_id]).convert("RGB")
        inputs = processor(
            text=prompt, images=image, return_tensors="pt"
        ).to("cuda", torch.float16)
        output = model.generate(
            **inputs, max_new_tokens=5, temperature=0.0, do_sample=False
        )
        raw   = processor.decode(output[0], skip_special_tokens=True)
        after = raw.split("A:")[-1].strip()
        print(f"Image {label} | Answer: {after}")
    print("---")

Image A | Answer: low
Image B | Answer: low
---
Image A | Answer: low
Image B | Answer: low
---
Image A | Answer: low
Image B | Answer: low
---
Image A | Answer: low
Image B | Answer: low
---
Image A | Answer: low
Image B | Answer: low
---

In [ ]:
# Debug: check LLaVA score distribution for more depressing
import re

cues     = ATTRIBUTE_CUES.get("more depressing", [])
cue_text = ", ".join(cues)

prompt = f"""USER: <image>

Rate how depressing this place looks on a scale from 0 to 100.

Important visual cues may include:
{cue_text}

Be precise and use the full range when appropriate.
Avoid default or middle values unless necessary.
Use a wide range of scores to clearly distinguish between different scenes.
Do not give identical scores unless the two places truly look the same.

Answer ONLY with a number between 0 and 100.

ASSISTANT:"""

votes  = df_votes[df_votes["study_id"] == attribute_map["more depressing"]].copy()
sample = votes[
    votes["left"].isin(image_map.keys()) &
    votes["right"].isin(image_map.keys())
].sample(10, random_state=42)

scores = []
for _, row in sample.iterrows():
    for img_id, label in [(row["left"], "A"), (row["right"], "B")]:
        image  = Image.open(image_map[img_id]).convert("RGB")
        inputs = processor(
            text=prompt, images=image, return_tensors="pt"
        ).to("cuda", torch.float16)
        output = model.generate(
            **inputs, max_new_tokens=10, temperature=0.0, do_sample=False
        )
        raw   = processor.decode(output[0], skip_special_tokens=True)
        after = raw.split("ASSISTANT:")[-1].strip()
        match = re.search(r"\d+", after)
        score = int(match.group()) if match else None
        scores.append(score)
        print(f"Image {label} | Score: {after}")
    print("---")

valid = [s for s in scores if s is not None]
if valid:
    print(f"\nScore distribution — min: {min(valid)}, max: {max(valid)}, mean: {sum(valid)/len(valid):.1f}")

Image A | Score: 50
Image B | Score: 50
---
Image A | Score: 50
Image B | Score: 50
---
Image A | Score: 70
Image B | Score: 80
---
Image A | Score: 70
Image B | Score: 50
---
Image A | Score: 80
Image B | Score: 50
---
Image A | Score: 50
Image B | Score: 50
---
Image A | Score: 50
Image B | Score: 50
---
Image A | Score: 50
Image B | Score: 50
---
Image A | Score: 70
Image B | Score: 70
---
Image A | Score: 70
Image B | Score: 70
---

Score distribution — min: 50, max: 80, mean: 59.0

In [ ]:
# Debug: see raw CoT output for beautiful
cues     = ATTRIBUTE_CUES.get("beautiful", [])
cue_text = ", ".join(cues)

reasoning_prompt = f"""USER: <image>

Two places are shown side-by-side:

Image A (left)
Image B (right)

Your task is to determine which place looks more **beautiful**.

Important visual cues related to "beautiful" may include:
{cue_text}

Follow these steps:

Step 1: Briefly describe Image A focusing on relevant cues.
Step 2: Briefly describe Image B focusing on relevant cues.
Step 3: Compare both images based on those cues.
Step 4: Decide which image better represents "beautiful".

IMPORTANT:
Give your final answer EXACTLY in this format on a new line:
Answer: A
or
Answer: B

ASSISTANT:
"""

votes  = df_votes[df_votes["study_id"] == attribute_map["beautiful"]].copy()
sample = votes[
    votes["left"].isin(image_map.keys()) &
    votes["right"].isin(image_map.keys())
].sample(5, random_state=42)

for idx, (_, row) in enumerate(sample.iterrows()):
    img_A = image_map[row["left"]]
    img_B = image_map[row["right"]]
    combined = concatenate_images(img_A, img_B)
    inputs = processor(
        text=reasoning_prompt, images=combined, return_tensors="pt"
    ).to("cuda", torch.float16)
    output = model.generate(
        **inputs, max_new_tokens=80, temperature=0.0, do_sample=False
    )
    raw = processor.decode(output[0], skip_special_tokens=True)
    after = raw.split("ASSISTANT:")[-1].strip()
    print(f"=== Sample {idx+1} ===")
    print(after)
    print()

=== Sample 1 ===
Answer: B

=== Sample 2 ===
Answer: A

=== Sample 3 ===
Answer: B

=== Sample 4 ===
Answer: A

=== Sample 5 ===
Answer: B